/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frm_awal.java
 *
 * Created on Jul 25, 2016, 2:37:56 PM
 */
package daftartamuhotel;

/**
 *
 * @author User
 */
public class frm_awal extends javax.swing.JFrame {

    /** Creates new form frm_awal */
    public frm_awal() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        menu_registrasi = new javax.swing.JButton();
        menu_identitas = new javax.swing.JButton();
        menu_kamar = new javax.swing.JButton();
        menu_fasilitas = new javax.swing.JButton();
        menu_pembayaran = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menu_about = new javax.swing.JMenu();
        menu_logout = new javax.swing.JMenu();
        menu_keluar = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        menu_dataidentitas = new javax.swing.JMenu();
        menu_datakamar = new javax.swing.JMenu();
        Menu_datafasilitas = new javax.swing.JMenu();
        menu_datapembayaran = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1469360680_hotel.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 48));
        jLabel2.setText("*** Hotel Informatika ***");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(74, 74, 74))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        menu_registrasi.setFont(new java.awt.Font("Tahoma", 1, 12));
        menu_registrasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1466277703_19.png"))); // NOI18N
        menu_registrasi.setText("Registrasi Tamu");
        menu_registrasi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, null, null));
        menu_registrasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_registrasiActionPerformed(evt);
            }
        });

        menu_identitas.setFont(new java.awt.Font("Tahoma", 1, 12));
        menu_identitas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1469149959_Icon_Business_Set_00011_A.png"))); // NOI18N
        menu_identitas.setText("Data Identitas");
        menu_identitas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, null, null));
        menu_identitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_identitasActionPerformed(evt);
            }
        });

        menu_kamar.setFont(new java.awt.Font("Tahoma", 1, 12));
        menu_kamar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1469147293_bedroom.png"))); // NOI18N
        menu_kamar.setText("Data Kamar");
        menu_kamar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, null, null));
        menu_kamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_kamarActionPerformed(evt);
            }
        });

        menu_fasilitas.setFont(new java.awt.Font("Tahoma", 1, 12));
        menu_fasilitas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1468905188_ic_local_laundry_service_48px.png"))); // NOI18N
        menu_fasilitas.setText("Data Fasilitas");
        menu_fasilitas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, null, null));
        menu_fasilitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_fasilitasActionPerformed(evt);
            }
        });

        menu_pembayaran.setFont(new java.awt.Font("Tahoma", 1, 12));
        menu_pembayaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1469149262_resolutions-16.png"))); // NOI18N
        menu_pembayaran.setText("Data Pembayaran");
        menu_pembayaran.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, null, null));
        menu_pembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_pembayaranActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(menu_registrasi, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(menu_identitas, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(menu_kamar, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(menu_fasilitas, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(menu_pembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menu_registrasi, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menu_identitas, javax.swing.GroupLayout.PREFERRED_SIZE, 87, Short.MAX_VALUE)
                    .addComponent(menu_kamar, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                    .addComponent(menu_fasilitas, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                    .addComponent(menu_pembayaran, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
                .addContainerGap())
        );

        jMenu1.setText("File");

        menu_about.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1469434798_Info.png"))); // NOI18N
        menu_about.setText("Tentang Pembuat");
        menu_about.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_aboutMouseClicked(evt);
            }
        });
        jMenu1.add(menu_about);

        menu_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1469434283_logout.png"))); // NOI18N
        menu_logout.setText("Log Out");
        menu_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_logoutMouseClicked(evt);
            }
        });
        jMenu1.add(menu_logout);

        menu_keluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1468182599_Close_Box_Red.png"))); // NOI18N
        menu_keluar.setText("Keluar");
        menu_keluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_keluarMouseClicked(evt);
            }
        });
        jMenu1.add(menu_keluar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("View");

        menu_dataidentitas.setText("DataIdentitasTamu");
        menu_dataidentitas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_dataidentitasMouseClicked(evt);
            }
        });
        jMenu2.add(menu_dataidentitas);

        menu_datakamar.setText("Datakamar");
        menu_datakamar.setActionCommand("DataKamar");
        menu_datakamar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_datakamarMouseClicked(evt);
            }
        });
        jMenu2.add(menu_datakamar);

        Menu_datafasilitas.setText("DataFasilitasTambahan");
        Menu_datafasilitas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu_datafasilitasMouseClicked(evt);
            }
        });
        jMenu2.add(Menu_datafasilitas);

        menu_datapembayaran.setText("DataPembayaran");
        menu_datapembayaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_datapembayaranMouseClicked(evt);
            }
        });
        jMenu2.add(menu_datapembayaran);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void menu_registrasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_registrasiActionPerformed
// TODO add your handling code here:
    frm_id id = new frm_id();
    id.setVisible(true);
}//GEN-LAST:event_menu_registrasiActionPerformed

private void menu_identitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_identitasActionPerformed
// TODO add your handling code here:
    data_identitas dataid = new data_identitas();
    dataid.setVisible(true);
}//GEN-LAST:event_menu_identitasActionPerformed

private void menu_kamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_kamarActionPerformed
// TODO add your handling code here:
    data_kamar datakamar = new data_kamar();
    datakamar.setVisible(true);
}//GEN-LAST:event_menu_kamarActionPerformed

private void menu_fasilitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_fasilitasActionPerformed
// TODO add your handling code here:
    data_fasilitastambahan datafasilitas = new data_fasilitastambahan();
    datafasilitas.setVisible(true);
}//GEN-LAST:event_menu_fasilitasActionPerformed

private void menu_pembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_pembayaranActionPerformed
// TODO add your handling code here:
    data_pembayaran databayar = new data_pembayaran();
    databayar.setVisible(true);
}//GEN-LAST:event_menu_pembayaranActionPerformed

private void menu_keluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_keluarMouseClicked
// TODO add your handling code here:
    dispose();
}//GEN-LAST:event_menu_keluarMouseClicked

private void menu_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_logoutMouseClicked
// TODO add your handling code here:
    frm_login login = new frm_login();
    login.setVisible(true);
    dispose();
}//GEN-LAST:event_menu_logoutMouseClicked

private void menu_aboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_aboutMouseClicked
// TODO add your handling code here:
    tentang about = new tentang();
    about.setVisible(true);
}//GEN-LAST:event_menu_aboutMouseClicked

private void menu_dataidentitasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_dataidentitasMouseClicked
// TODO add your handling code here:
    data_identitas dataid = new data_identitas();
    dataid.setVisible(true);
}//GEN-LAST:event_menu_dataidentitasMouseClicked

private void menu_datakamarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_datakamarMouseClicked
// TODO add your handling code here:
    data_kamar datakamar = new data_kamar();
    datakamar.setVisible(true);
}//GEN-LAST:event_menu_datakamarMouseClicked

private void Menu_datafasilitasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu_datafasilitasMouseClicked
// TODO add your handling code here:
    data_fasilitastambahan datafasilitas = new data_fasilitastambahan();
    datafasilitas.setVisible(true);
}//GEN-LAST:event_Menu_datafasilitasMouseClicked

private void menu_datapembayaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_datapembayaranMouseClicked
// TODO add your handling code here:
    data_pembayaran databayar = new data_pembayaran();
    databayar.setVisible(true);
}//GEN-LAST:event_menu_datapembayaranMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_awal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_awal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_awal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_awal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new frm_awal().setVisible(true);
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Menu_datafasilitas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenu menu_about;
    private javax.swing.JMenu menu_dataidentitas;
    private javax.swing.JMenu menu_datakamar;
    private javax.swing.JMenu menu_datapembayaran;
    private javax.swing.JButton menu_fasilitas;
    private javax.swing.JButton menu_identitas;
    private javax.swing.JButton menu_kamar;
    private javax.swing.JMenu menu_keluar;
    private javax.swing.JMenu menu_logout;
    private javax.swing.JButton menu_pembayaran;
    private javax.swing.JButton menu_registrasi;
    // End of variables declaration//GEN-END:variables
}
